---
version: "3"
services:
  pycatdetector:
    build: .
    image: blinkstick_square:latest
    container_name: blinkstick_square
    ports:
      - '8000:8000'
    environment:
      - TZ=Europe/Berlin
      - BS_SQ_API_USERNAME=${BS_SQ_API_USERNAME}  # Do not hardcode here!
      - BS_SQ_API_PASSWORD=${BS_SQ_API_PASSWORD}  # Do not hardcode here!
    volumes:
    - ./logging.conf:/opt/blinkstick_square/logging.conf:ro
    - ./logs:/opt/blinkstick_square/logs:rw
    restart: always
    privileged: true

# networks:
#  default:
#    name: containers
#    external: true